name: flutter_online_shop
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  #flutter_svg: ^0.20.0-nullsafety.3
  flutter_html: ^1.3.0
  flutter_custom_clippers: ^1.1.2
  dio: ^3.0.10
  provider: ^5.0.0
  razorpay_flutter: ^1.2.5
  shared_preferences: ^2.0.5
  #flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/items/
    - assets/images/ipads/
    - assets/images/iphones/
    - assets/images/macbook/
    - assets/images/iphone_batteries/
    - assets/images/iphone_covers/
    - assets/images/iphone_screens/
    - assets/images/screen_protection/
    - assets/images/tools_and_equipment/
    - assets/images/macbook_charger/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300